#!/bin/bash

#------------------------------------------------------------------------
# helm init for tiller.
# see tiller
# https://helm.sh/docs/glossary/
#------------------------------------------------------------------------
set -e

# script directory
SCRIPT_DIR=$(cd $(dirname $0); pwd)

IS_TILLER_INSTALL=$(kubectl get serviceaccount -n kube-system | grep tiller | wc -l | tr -d '\n')
if [ $IS_TILLER_INSTALL -eq "0" ]; then
    kubectl apply -f $SCRIPT_DIR/files/helm-rbac.yaml
    helm init --service-account tiller --node-selectors "beta.kubernetes.io/os"="linux"
else
    echo "Tiller already created."
#    helm init upgrade
fi

# Check tiller
while true
do
    IS_SET_HELM=$(helm version | grep Server | wc -l | tr -d '\n')
    if [ $IS_SET_HELM -eq "1" ]; then
        break
    fi
    sleep 3
done
kubectl get serviceaccount -n kube-system | grep tiller
echo "Tiller server runs."
