#!/bin/bash

echo "------------------------------------------------------------------------"
echo "azure cluster creadencials"
echo "------------------------------------------------------------------------"
echo "az aks get-credentials --resource-group {resource group} --name {cluster name}"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "create Development/Pod/ReplicaSet/Service/Ingress"
echo "------------------------------------------------------------------------"
echo "kubectl create -f {yaml}"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "update Development/Pod/ReplicaSet/Service/Ingress"
echo "------------------------------------------------------------------------"
echo "kubectl apply -f {yaml}"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "get pod log"
echo "-f equals tail -f"
echo "--timestamps=true displays timestamp"
echo "------------------------------------------------------------------------"
echo "kubectl get po"
echo "kubectl logs -f {NAME}"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "describe information"
echo "------------------------------------------------------------------------"
echo "kubectl describe {po|no|svc|rc} {name}"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "execute command on pod"
echo "------------------------------------------------------------------------"
echo "kubectl exec {pod name} {command}"
echo "ex) kubectl exec nginx-6788fdccc8-g654t cat /etc/nginx/conf.d/proxy.conf"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "check api resources"
echo "APIGROUP is empty, apiVersion sets v1, but APIGROUP is not empty, check 'kuberctl api-versions' command."
echo "------------------------------------------------------------------------"
echo "kubectl api-resources"
echo "ex) kubectl api-resources | grep Deployment"
echo -e "\n"

echo "------------------------------------------------------------------------"
echo "check api versions"
echo "------------------------------------------------------------------------"
echo "kubectl api-versions"
echo "ex) kubectl api-resources | grep extensions"
echo -e "\n"
