#!/bin/bash
#--------------------------------------------------------------
# This script runs terraform command and create main_init.tf file.
# main_init.tf generates terraform backend block and provider(azurerm/azuread).
# 
# if you want to run this script, need to add this following environment.
# - ENV
# - ARM_CLIENT_ID
# - ARM_CLIENT_SECRET
# - ARM_SUBSCRIPTION_ID
# - STORAGE_ACCOUNT_NAME
# - RESOURCE_GROUP_NAME
# - CONTAINER_NAME
# - IS_GENERATE_PROVIDER
# 
# usage
# ex) tf plan
# ex) tf apply
#--------------------------------------------------------------
set -e

# name
NAME=`basename $0`

# usage function
function usage () {
  echo "terraform needs $1 environment parameter."
  echo "usage: ${NAME} {command...}" 1>&2
  exit 1
}

# script directory
SCRIPT_DIR=$(cd $(dirname $0); pwd)

# arguments
COMMAND=$@

# terraform key
if [ -e "terraform-state.key" ]; then
  KEY=`cat terraform-state.key | sed -e "s/[\r\n]\+//g"`
else
  KEY=terraform-tfstate
fi

# if [ $COMMAND = "destroy" ]; then
#   echo "terraform destroies command can't access now."
#   exit 1
# fi

# check environment
if [ -z $ENV ]; then
  usage ENV
  exit 1
fi
if [ -z $ARM_CLIENT_ID ]; then
  usage ARM_CLIENT_ID
  exit 1
fi
if [ -z $ARM_CLIENT_SECRET ]; then
  usage ARM_CLIENT_SECRET
  exit 1
fi
if [ -z $ARM_TENANT_ID ]; then
  usage ARM_TENANT_ID
  exit 1
fi
if [ -z $ARM_SUBSCRIPTION_ID ]; then
  usage ARM_SUBSCRIPTION_ID
  exit 1
fi
if [ -z $STORAGE_ACCOUNT_NAME ]; then
  usage STORAGE_ACCOUNT_NAME
  exit 1
fi
if [ -z $RESOURCE_GROUP_NAME ]; then
  usage RESOURCE_GROUP_NAME
  exit 1
fi
if [ -z $CONTAINER_NAME ]; then
  usage CONTAINER_NAME
  exit 1
fi
if [ -z $IS_GENERATE_PROVIDER ]; then
  usage IS_GENERATE_PROVIDER
  exit 1
fi

# export TF_LOG=1
# export TF_LOG_PATH='./terraform.log'
rm -f terraform.log crash.log main_init.tf
if [ $IS_GENERATE_PROVIDER -eq "1" ]; then
    cat $SCRIPT_DIR/files/main.template.tf | sed -e "s/##STORAGE_ACCOUNT_NAME##/${STORAGE_ACCOUNT_NAME}/g" > ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##CONTAINER_NAME##@${CONTAINER_NAME}@g" ./main_init.tf
    cat ./main_init.tf | sed -i -e "s@##KEY##@${KEY}@g" ./main_init.tf
fi
terraform init
terraform $COMMAND -var-file=terraform.$ENV.tfvars 
