#--------------------------------------------------------------
# base build image
#--------------------------------------------------------------
ARG TERRAFORM_VERSION=latest
FROM ymiyazakixyz/terraform-azure:${TERRAFORM_VERSION}
