#!/bin/bash
set -eu

if [ "$DOCKER_TAG" == "latest" ]; then
    docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} .
else
    docker build --build-arg TERRAFORM_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME} .
fi
